server:
  port: 8000
spring:
  application:
    name: server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 自己本来就是server，不用自己注册自己
    fetch-registry: false # 自己本来就是server，不用从server拉取信息
    eureka-server-u-r-l-context: http://${eureka.instance.hostname}:${server.port}/eureka/